API_KEY=wMG8GrrZMBFeZMCWJTqTzZns7B4w
BASE_URL=https://api.tradier.com/v1
ALETHEIA_KEY=your_actual_aletheia_key
MARKETAUX_KEY=your_actual_marketaux_key
SECRET_KEY=TU_SECRET_KEY
USERS_FILE=users.csv


INITIAL_PASSWORDS=abc234,def456,ghi789,jkl010,mno345,pqr678,stu901,vwx234,yz1234,abcd56,efgh78,ijkl90,mnop12,qrst34,uvwx56,yzab78,cdef90,ghij12,news34,opqr56,xyz789,kml456,nop123,qwe987,asd654,zxc321,bnm098,vfr765,tgb432,hju109
FMP_API_KEY = "bQ025fPNVrYcBN4KaExd1N3Xczyk44wM"
TRADIER_API_KEY = "Mys3Hsfg4oG5G6qi9PF7ZfInDDVf"
